# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('account_child_id', models.IntegerField()),
                ('potential', models.CharField(max_length=200)),
                ('pipeline', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('account_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('account_risk', models.CharField(max_length=100)),
            ],
        ),
    ]
